#!/usr/bin/env bash
# plugins/compile <build-dir> <cache-dir>

# parse args
PLUGINS_DIR=`cd $(dirname $0); pwd`
BUILD_DIR=$1
CACHE_DIR=$2

# clean up leaking environment
unset GIT_DIR

function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}

##################################################
# Building Bootstrap...
##################################################
echo "-----> Building Bootstrap... " | indent
BOOTSTRAP=$PLUGINS_DIR/bootstrap/css/bootstrap.scss
BOOTSTRAP_LESS=$PLUGINS_DIR/less/bootstrap.less
BOOTSTRAP_RESPONSIVE=$PLUGINS_DIR/bootstrap/css/bootstrap-responsive.scss
BOOTSTRAP_RESPONSIVE_LESS=$PLUGINS_DIR/bootstrap/less/responsive.less
if [[ ! -d $PLUGINS_DIR/bootstrap/css ]]; then
  mkdir $PLUGINS_DIR/bootstrap/css
fi
recess --compile ${BOOTSTRAP_LESS} > ${BOOTSTRAP}
recess --compile ${BOOTSTRAP_RESPONSIVE_LESS} > ${BOOTSTRAP_RESPONSIVE}
echo "       done."