#!/usr/bin/env bash
# plugins/compile <build-dir> <cache-dir>

# fail fast
set -e

# parse args
BUILD_DIR=$1
CACHE_DIR=$2

# clean up leaking environment
unset GIT_DIR

function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}

BOOTSTRAP=./bootstrap/css/bootstrap.scss
BOOTSTRAP_LESS=./bootstrap/less/bootstrap.less
BOOTSTRAP_RESPONSIVE=./bootstrap/css/bootstrap-responsive.scss
BOOTSTRAP_RESPONSIVE_LESS=./bootstrap/less/responsive.less
mkdir ./bootstrap/css
recess --compile ${BOOTSTRAP_LESS} > ${BOOTSTRAP}
recess --compile ${BOOTSTRAP_RESPONSIVE_LESS} > ${BOOTSTRAP_RESPONSIVE}